Types and operators hm
agbelousova/AQA_MTS pull request #1
Opened 2023-11-17 15:23 UTC by agbelousova

homework completed

2023-11-19 20:54 UTC, wildpioneer requested changes

2023-11-19 20:54 UTC, wildpioneer commented on Aqa_MTS/TypesAndOperators/TypeAndOperators_HM.cs
> +int chislo = Convert.ToInt32(chisloString);
Отсутствует проверка что введенное число принадлежить промежутку -50; 50

2023-11-19 20:54 UTC, wildpioneer commented on Aqa_MTS/TypesAndOperators/TypeAndOperators_HM.cs
> +switch (chislo % 2 == 0)
:)))) Ну не совсем так - ну да ладно ;)

2023-11-20 09:26 UTC, agbelousova commented
Исправила проверку, что введенное число принадлежит промежутку -50; 50

2023-11-27 18:54 UTC, closed without merging