N unit new hm
agbelousova/AQA_MTS pull request #12
Opened 2024-01-26 17:11 UTC by agbelousova

Не знаю, правильно ли я поняла ДЗ.
Но сделала как поняла.)

2024-01-29 09:34 UTC, wildpioneer requested changes

2024-01-29 09:34 UTC, wildpioneer commented on Aqa_MTS/NUnitProjectHM/Calc.cs
> +    public static int DivInt(int x, int y) => x / y;
А почему методы называются по разному? Повтори тему перегрузки методов и Generic

2024-01-29 09:34 UTC, wildpioneer commented on Aqa_MTS/NUnitProjectHM/TestCase.cs
> +        if (Convert.ToInt32(d) != 0)
Не понимаю, зачем тут трансформация в Int выполняется - ведь ты ты и так сама определяешь набор данных для данного теста

2024-01-29 09:34 UTC, wildpioneer commented on Aqa_MTS/NUnitProjectHM/TestCase.cs
> +            Console.WriteLine("Деление на 0!");
Тут не совсем верно - в случае с double есть нюанс деления на 0 - это будет double.NaN

2024-01-29 09:34 UTC, wildpioneer commented on Aqa_MTS/NUnitProjectHM/TestCase.cs
> +    [TestCaseSource(typeof(TestData), nameof(TestData.DivideCases))]
Наборы данных лучше разделить для каждого случая в отдельности

2024-01-29 09:34 UTC, wildpioneer commented on Aqa_MTS/NUnitProjectHM/TestCase.cs
> +    [Category("Smoke")]
Не хватает тестов на другие аттрибуты - retry, repeat, parewise и т.д.

2024-01-29 16:46 UTC, agbelousova commented
Внесла правки

2024-02-05 16:59 UTC, wildpioneer approved these changes

2024-02-05 16:59 UTC, wildpioneer commented
Проверено

2024-02-05 16:59 UTC, closed without merging