Selenium advanced hm
agbelousova/AQA_MTS pull request #15
Opened 2024-02-07 17:40 UTC by agbelousova

Сделала ДЗ по Selenium. Advanced

2024-02-12 20:45 UTC, wildpioneer requested changes

2024-02-12 20:45 UTC, wildpioneer commented on Aqa_MTS/SeleniumAdvanced/HomeWork/SeleniumWebDriverTest.cs
> +       IWebElement messageRemoveElement = WaitsHelper.FluentWaitForElement(By.XPath("//form[@id='checkbox-example']/p"));
1. Есть ID - нужен ли здесь XPath?
2. Почему Fluent ожидание?

2024-02-12 20:45 UTC, wildpioneer commented on Aqa_MTS/SeleniumAdvanced/HomeWork/SeleniumWebDriverTest.cs
> +       IWebElement elementInput = Driver.FindElement(By.XPath("//form[@id='input-example']/input"));
Опять же - почему XPath - как я вижу css будет значительно проще

2024-02-12 20:45 UTC, wildpioneer commented on Aqa_MTS/SeleniumAdvanced/HomeWork/SeleniumWebDriverTest.cs
> +       Thread.Sleep(2000);//чтоб успеть увидеть результат
Нужно сделать правильную проверку - и не использовать Sleep

2024-02-16 19:29 UTC, agbelousova commented
Исправила

2024-03-05 11:10 UTC, wildpioneer commented
Проверено

2024-03-05 11:10 UTC, closed without merging